import { describe, expect, it } from "vitest";
import { Word } from "./entities";

describe("Word", () => {
  it("should create a new Word instance", () => {
    const word = Word.create({
      wordBookId: 1,
      term: "test term",
      meaning: "test meaning",
    });

    expect(word).toBeInstanceOf(Word);
    expect(word.id).toBe(0); // id is 0 as it's generated by DB
    expect(word.wordBookId).toBe(1);
    expect(word.term).toBe("test term");
    expect(word.meaning).toBe("test meaning");
    expect(word.createdAt).toBeInstanceOf(Date);
  });

  it("should create a Word instance from persistence", () => {
    const now = new Date();
    const word = Word.fromPersistence({
      id: 100,
      wordBookId: 2,
      term: "persisted term",
      meaning: "persisted meaning",
      createdAt: now,
    });

    expect(word).toBeInstanceOf(Word);
    expect(word.id).toBe(100);
    expect(word.wordBookId).toBe(2);
    expect(word.term).toBe("persisted term");
    expect(word.meaning).toBe("persisted meaning");
    expect(word.createdAt).toBe(now);
  });
});
