services:
  app-prod:
    container_name: app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db-prod:5432/app_db
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db-prod
    restart: always

  db-prod:
    image: postgres:17-alpine
    container_name: db-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db_data_prod:
