import { describe, expect, it } from "vitest";
import { WordBook } from "./entities";

describe("WordBook", () => {
  it("should create a new WordBook instance", () => {
    const wordBook = WordBook.create({
      userId: 1,
      title: "My First WordBook",
    });

    expect(wordBook).toBeInstanceOf(WordBook);
    expect(wordBook.id).toBe(0); // id is 0 as it's generated by DB
    expect(wordBook.userId).toBe(1);
    expect(wordBook.title).toBe("My First WordBook");
  });

  it("should create a WordBook instance from persistence", () => {
    const wordBook = WordBook.fromPersistence({
      id: 100,
      userId: 2,
      title: "Persisted WordBook",
    });

    expect(wordBook).toBeInstanceOf(WordBook);
    expect(wordBook.id).toBe(100);
    expect(wordBook.userId).toBe(2);
    expect(wordBook.title).toBe("Persisted WordBook");
  });
});
