export class WordBook {
  readonly id: number;
  readonly userId: number;
  readonly title: string;

  private constructor(id: number, userId: number, title: string) {
    this.id = id;
    this.userId = userId;
    this.title = title;
  }

  static create(props: { userId: number; title: string }): WordBook {
    // id will be generated by the database
    return new WordBook(0, props.userId, props.title);
  }

  static fromPersistence(props: {
    id: number;
    userId: number;
    title: string;
  }): WordBook {
    return new WordBook(props.id, props.userId, props.title);
  }
}
